# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
# https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
# https://docs.fastlane.tools/plugins/available-plugins

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

	opt_out_usage

	#setup_ci( #force: true)

  	desc "Build iOS"

  	lane :create_my_keychain do

		# sh("security list-keychains -d user")

		increment_build_number(
			build_number: Time.now.to_i # Ruby method
		)

		create_keychain(
			name: "my_fastlane_keychain",
			unlock: true,
			password: "b_Sprad83",
			timeout: 3600,
			#default_keychain: true,
			add_to_search_list: true,
			require_create: true,
		)
  	end

	lane :get_my_provisioning do

		get_provisioning_profile( # invokes sigh
			username: "badsprad@icloud.com"
		)
	end

	lane :update_my_provisioning do

		update_code_signing_settings(
			use_automatic_signing: false,
			path: "MyTestApp.xcodeproj"
		)

		update_project_provisioning(
			xcodeproj: "MyTestApp.xcodeproj",
			profile: "Appstore_com.testapp.domain.mobileprovision",
			# build_configuration: "Release",
			code_signing_identity: "iPhone Distribution: My Company Test App"
		)

		update_project_team(
			path: "MyTestApp.xcodeproj",
			teamid: "TPTVYTBHA6"
		)
	end

	lane :build_my_app do

		build_app(
			export_method: "app-store", #app-store, ad-hoc, package, enterprise, development, developer-id
		)
	end

	lane :upload_my_app do

		update_code_signing_settings(
			use_automatic_signing: false,
			path: "MyTestApp.xcodeproj"
		)

		upload_to_testflight(
			skip_submission: true, 		# to only upload the build
			beta_app_feedback_email: "support@email.com",
			beta_app_description: "This is a description of my app",
			demo_account_required: false,
			notify_external_testers: false,
			changelog: "This is my changelog of things that have changed in a log",
			ipa: "build/my-test-app.ipa"
		)
	end

	lane :delete_my_keychain do

		delete_keychain(
			name: "my_fastlane_keychain",
		)
	end

end
